channels:
- conda-forge
dependencies:
- python=3.9.7
- pip
- pip:
  - mlflow
  - boto3==1.20.44
  - keras==2.7.0
  - pandas==1.4.0
  - pillow==9.0.0
  - pydot==1.4.2
  - pyopenssl==21.0.0
  - scipy==1.7.3
  - tensorflow-gpu==2.7.0
  - tensorflow==2.6.0
name: mlflow-env
